[package]
name = "ghstats"
version = "2.0.0"
edition = "2024"
authors = ["Alexandre Hallaine <alexandre@hallaine.com>"]

[dependencies]
reqwest = { version = "0.12", features = ["blocking", "gzip"] }
flate2 = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
