[package]
name = "ghstats"
version = "1.0.0"
edition = "2024"
authors = ["Alexandre Hallaine <alexandre@hallaine.com>"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = "0.4"
