name: Daily Stats

on:
  schedule:
    - cron: "30 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Store date
        run: echo "DATE=$(date -u -d 'yesterday' +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Process
        run: cargo run -- $DATE >> stats/$DATE.json

      - name: Commit and push stats
        run: |
          git add stats/$DATE.json
          git commit -m "chore(daily): stats for $DATE"
          git push
