name: Daily Stats

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Store date
        run: echo "DATE=$(date -u -d '2 days ago' +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Download
        run: ./scripts/download.sh $DATE
      - name: Analyze
        run: ./scripts/analyze.sh $DATE

      - name: Commit and push output
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add output
          git commit -m "chore(daily): stats for $DATE"
          git push
